-- CREATE

CREATE TABLE USER (
	ID_USER int auto_increment NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	STATUS int NOT NULL,
	PRIMARY KEY (`ID_USER`)
);

CREATE TABLE ROLE (
	ID_ROLE int auto_increment NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CODE VARCHAR(30) NOT NULL,
	PRIMARY KEY (`ID_ROLE`)
);